### ISSUE TITLE
The instructions for setup on OSX are a little hard to read

### ISSUE THREAD

**Issue by CorySpitzer** [ShiftGithub/shiftcal#37]
Specifically, the `code` snippets don't look different from the rest of the Readme.

**Comment by tommctighe** [comment]
We might also just link to MAMP: https://www.mamp.info/en/
Well-documented, easy localhost set-up...plus it's fun to say "MAMP!"

**Comment by CorySpitzer** [comment]
Yeah, that might work for OSX and Windows, but not those running other OS's like me (Ubuntu).

Also, this is just about making the Readme easier to read.

**Comment by georgemandis** [comment]
Agree it's definitely more readable.

How about we link to [XAMPP](https://www.apachefriends.org/index.html)?

It's... a little bit weirder to say. But more platform agnostic :)

**Comment by CorySpitzer** [comment]
'Xampp' sounds good to me :)
